# Si se realiza un cambio en este archivo,
# se debe reiniciar el visual para que se
# implementen los cambios.

COLUMNAS_SELECCIONADAS = [
    'DIA', 'EE Planta / Hl', 'EE Elaboracion / Hl', 'EE Bodega / Hl', 'EE Cocina / Hl',
    'EE Envasado / Hl', 'EE Linea 2 / Hl', 'EE Linea 3 / Hl', 'EE Linea 4 / Hl', 
    'EE Servicios / Hl', 'EE Sala Maq / Hl', 'EE Frio / Hl', 'EE Aire / Hl', 
    'EE CO2 / Hl', 'EE Caldera / Hl', 'EE Eflu / Hl', 'EE Agua / Hl', 
    'EE Resto Serv / Hl', 'EE Resto Planta / Hl', 'Agua Planta / Hl', 
    'Agua Elab / Hl', 'Agua Bodega / Hl', 'Agua Cocina / Hl', 'Agua Envas / Hl', 
    'Agua Linea 2/Hl', 'Agua Linea 3/Hl', 'Agua Linea 4/Hl', 'Agua Servicios/Hl', 
    'Agua Planta de Agua/Hl', 'Produccion Agua / Hl', 'ET Planta / Hl', 
    'ET Elab/Hl', 'ET Bodega/Hl', 'ET Cocina/Hl', 'ET Envasado/Hl', 'ET Linea 2/Hl', 
    'ET Linea 3/Hl', 'ET Linea 4/Hl', 'ET Servicios / Hl', 'Aire Planta / Hl', 
    'Aire Elaboracion / Hl', 'Aire Cocina / Hl', 'Aire Bodega / Hl', 
    'Aire Envasado / Hl', 'Aire L2 / Hl', 'Aire L3 / Hl', 'Aire L4 / Hl', 
    'Aire Servicios / Hl', 'CO 2 / Hl', 'CO 2 Filtro / Hl', 'CO 2 linea 3 / Hl', 
    'CO 2 Linea 4 / Hl', 'Hl de Mosto', 'Hl Cerveza Cocina', 'Hl Producido Bodega', 
    'Hl Cerveza Filtrada', 'Hl Cerveza Envasada', 'Hl Cerveza L2', 'Hl Cerveza L3', 
    'Hl Cerveza L4', 'Hl Cerveza L5', 'Cocimientos Diarios', 'HL Mosto Tecate', 
    'HL Mosto Heineken', 'HL Mosto Sol', 'HL Mosto Miller', 'HL Mosto IPA', 
    ' HL Mosto Golden', 'HL Mosto Amstel Lager', 'HL Cerveza Sin Diliuir A90', 
    'HL Cerceza Sin Diluir A190', 'Nivel Silo Bagazo Sur (2)', 'Planta (Kw)', 
    'Elaboracion (Kw)', 'Bodega (Kw)', 'Cocina (Kw)', 'Envasado (Kw)', 
    'Linea 2 (Kw)', 'Linea 3 (Kw)', 'Linea 4 (Kw)', 'Servicios (Kw)', 
    'Sala Maq (Kw)', 'Aire (Kw)', 'Calderas (Kw)', 'Efluentes (Kw)', 'Frio (Kw)', 
    'Pta Agua / Eflu (Kw)', 'Prod Agua (Kw)', 'Resto Serv (Kw)', 'Restos Planta (Kw)', 
    'KW Gral Planta', 'KW Trafo 4', 'KW Trafo 5', 'KW Trafo 11', 'KW Trafo 12', 
    'KW Linea 2', 'KW Mycom 1', 'KW Mycom 2', 'KW Mycom 3', 'KW Mycom 4', 
    'KW Mycom 5', 'KW Mycom 6', 'KW Mycom 7', 'KW Trafo 9', 'KW Trafo 10', 
    'KW Cocina', 'Kw Molino', 'KW Linea 3 y 4', 'KW Linea 3', 'KW Servicio L2', 
    'KW Planta de Agua', 'Kw Casona', 'KW Laboratorio', 'Kw Admininistracion', 
    'KW Pta Agua/Log', 'KW Bba Glicol Sala MAq', 'KW Comp Kaeser', 
    'KW Iluminacion L3', 'KW Iluminacion L4', 'KW Ilum Dep L3/L4', 
    'KW Cond 5. 6 y 9', 'KW Cond 7. 8 y 11', 'KW Cond 11. 12 y 13', 
    'KW Bba Glicol Bod', 'KW CO2', 'KW Secador Kaeser', 'KW Caldera 3', 
    'KW Caldera 4', 'KW Filtr Carbon', 'KW Atlas 3', 'KW Toma Agua', 
    'KW Enfr Agua Cocina', 'KW Enfluentes Coc', 'KW Enfluente Efl', 
    'KW Enfluentes Hidr', 'KW Obrador Contratistas', 'Kw Compresores Aire', 
    'Kw Linea Barriles', 'Agua Planta (Hl)', 'Agua Elaboracion (Hl)', 
    'Agua Bodega (Hl)', 'Agua Cocina (Hl)', 'Agua Dilucion (Hl)', 
    'Agua Envasado (Hl)', 'Agua Servicios (Hl)', 'Planta de agua (Hl)', 
    'Produccion (Hl)', 'Red L1 y L2', 'FC L1 y L2', 'FC Lavadora L2', 'Red L3', 
    'FC Lavadora L3', 'Red Paste L4', 'FC Barriles', 'Red Paste L1', 'FC Linea 3', 
    'Rinser', 'Red Bodega', 'FC CIP Bodega', 'FC Centec I', 'FC Cocina', 
    'FC Centec II', 'Agua Cond REC', 'Agua Red Servicios', 'Agua Cald', 
    'Agua Cist Industrial', 'Rep Agua Puerto', 'Agua Helada Cocina', 
    'Entrada Osmosis', 'Rechazo Osmosis', 'Red Administracion', 
    'Filtro de Carbon', 'Assa', 'Red Paste L3', 'Red Lavadora L3', 'Dilución A90', 
    'Dilución A190', 'Red  Bodega Interno', 'Agua Planta CO2', 'Retorno Planta CO2', 
    'Agua Limpieza y Bbba Vacio L2', 'Agua Enjuagadora L2', 'Agua Lavadora L2', 
    'Temp Tq Intermedio', 'Conversion Kg/Mj', 'Gas Planta (Mj)', 
    'Vapor Elaboracion (Kg)', 'Vapor Cocina (Kg)', 'Vapor Envasado (Kg)', 
    'Vapor Servicio (Kg)', 'ET Elaboracion (Mj)', 'ET Envasado (Mj)', 
    'ET Servicios (Mj)', 'Tot_Vapor_L3_L4', 'VAPOR DE LINEA 1 Y 2 KG', 
    'VAPOR DE LINEA 4 KG', 'Tot_Vapor_CIP_Bodega', 'Vapor L3', 'M3_Tot_Gas', 
    'CAUDAL DE GAS CALDERA 1 M3', 'CAUDAL DE BIO-GAS M3', 'VAPOR DE CALDERA 3 KG', 
    'VAPOR DE CALDERA 4 KG', 'VAPOR COCINA 1 KG', 'VAPOR COCINA 2 KG', 
    'TOT AGUA DESAIREADA', 'Vapor Olla 1 (Ton)', '(Vapor Olla 2 (Ton)', 
    'Aire Producido (M3)', 'Aire Planta (M3)', 'Aire Elaboracion (m3)', 
    'Aire Envasado (M3)', 'Aire Servicios (M3)', 'Tot Aire Expulsion', 
    'Totalizador_Aire_Bodega', 'Totalizador_Aire_Cocina', 'Totalizador_Aire_L2', 
    'Totalizador_Aire_L3', 'Totaliador_Aire_L4', 'Totalizador_Aire_L5', 
    'Totalizador Sistema Kaeser', 'Tot Aire Servicio Logistica', 
    'Totalizador_L2_Barriles', 'Totalizador_L3', 'Totaliador_Latas', 
    'Totalizador_Bodega', 'Totalizador_Tq_Pulmon', 'Totalizador_Filtracion', 
    'Tot  Trasiego', 'Agua Lavadora L3 / Hl', 'Agua Paste L3 / Hl', 
    'Meta EE Planta', 'Meta Agua Planta', 'Meta ET Planta', 'Meta Aire Planta', 
    'Meta Agua Elab', 'Meta Agua Bodega', 'Meta Agua Cocina', 'Meta Agua Envas', 
    'Meta Agua Linea 2', 'Meta Agua Linea 3', 'Meta Agua Linea 4', 
    'Meta Agua Linea 5', 'Meta Agua Servicios', 'Meta Agua Planta de Agua', 
    'Meta Produccion Agua', 'Meta EE Elaboracion', 'Meta EE Bodega', 
    'Meta EE Cocina', 'Meta EE Envasado', 'Meta EE Linea 2', 'Meta EE Linea 3', 
    'Meta EE Linea 4', 'Meta EE Linea 5', 'Meta EE Servicios', 
    'Meta EE Sala Maq', 'Meta EE Frio', 'Meta EE Aire', 'Meta EE CO2', 
    'Meta EE Caldera', 'Meta EE Eflu', 'Meta EE Agua ', 'Meta EE Resto Serv', 
    'Meta EE Resto Planta', 'Meta ET Elab', 'Meta ET Bodega', 'Meta ET Cocina', 
    'Meta ET Envasado', 'Meta ET Linea 2', 'Meta ET Linea 3', 
    'Meta ET Linea 4', 'Meta ET Linea 5', 'Meta ET Servicios', 
    'Meta Aire Elaboracion', 'Meta Aire Cocina', 'Meta Aire Bodega', 
    'Meta Aire Envasado', 'Meta Aire L2', 'Meta Aire L3', 'Meta Aire L4', 
    'Meta Aire L5', 'Meta Aire Servicios', 'Hl de Mosto Copia', 
    'Agua Paste L3', 'Agua Lavadora L3', 'Agua Cond Evaporativos', 
    'Agua Calderas', 'Agua Efluentes', 'Agua CO2', 'Vapor_L5 (KG)', 
    'Tot Vap Paste L3 / Hora', 'Tot Vap Lav L3 / Hora', 'Medicion Gas Planta (M3)', 
    'Tot A40/240/50/60/Centec/Filtro', 'Tot  A130/330/430'
]
