# Si se realiza un cambio en este archivo,
# se debe reiniciar el visual para que se
# implementen los cambios.

COLUMNAS_SELECCIONADAS = [
    # obligatorias
    "DIA",
    "Frio (Kw)",
    "Hl de Mosto",
    # ------------

    "Sala Maq (Kw)",
    "Servicios (Kw)",
    "KW Gral Planta",
    "Planta (Kw)",
    "Agua Planta (Hl)",
    "Planta de agua (Hl)",
    "KW Trafo 10",
    "Produccion (Hl)",
    "Aire Producido (M3)",
    "Totalizador Sistema Kaeser",
    "Kw Compresores Aire",
    "Aire (Kw)",
    "Elaboracion (Kw)",
    "Aire Planta (M3)",
    "Temp Tq Intermedio",
    "Pta Agua / Eflu (Kw)",
    "KW Secador Kaeser",
    "Bodega (Kw)",
    "KW Trafo 11",
    "KW Trafo 9",
    "Efluentes (Kw)",
    "KW Trafo 5",
    "Agua Cond REC",
    "KW Enfluente Efl",
    "KW Obrador Contratistas",
    "Hl Producido Bodega",
    "KW Cond 5. 6 y 9",
    "KW Planta de Agua",
    "Tot L3. L4 y Planta de CO2",
    "Agua Envasado (Hl)",
    "Filtro de Carbon",
    "KW Bba Glicol Bod",
    "KW Linea 3 y 4",
    "Agua Elaboracion (Hl)",
    "KW Iluminacion L3",
    "Envasado (Kw)",
    "KW Servicio L2",
    "KW Trafo 4",
    "Aire Servicios (M3)",
    "Totalizador_Tq_Pulmon",
    "KW Pta Agua/Log",
    "Rep Agua Puerto",
    "Gas Planta (Mj)",
    "KW Laboratorio",
    "Agua Bodega (Hl)",
    "Agua Servicios (Hl)",
    "Aire Envasado (M3)",
    "Aire Elaboracion (m3)",
    "M3_Tot_Gas",
    "Red L3",
    "Totalizador_Aire_Cocina",
    "KW Cond 11. 12 y 13",
    "Produccion Agua / Hl",
    "Agua Enjuagadora L2",
    "Agua Cond Evaporativos",
    "KW Mycom 7",
    "Hl Cerveza Envasada",
    "ET Envasado (Mj)",
    "Hl Cerveza Filtrada",
    "Totalizador_Aire_Bodega",
    "Agua Dilucion (Hl)",
    "Vapor Envasado (Kg)",
    "KW Trafo 12",
    "Cocimientos Diarios",
    "KW Enfluentes Hidr",
    "Kw Molino",
    "KW Iluminacion L4",
    "Resto Serv (Kw)",
    "KW Comp Kaeser",
    "Linea 3 (Kw)",
    "Tot_Vapor_L3_L4",
    "Totalizador_Filtracion",
    "KW Enfluentes Coc",
    "KW Linea 3",
    "KW Ilum Dep L3/L4",
    "FC Cocina",
    "Agua Cocina (Hl)",
    "Agua Efluentes",
    "Linea 4 (Kw)",
    "KW Mycom 5",
    "Kw Linea Barriles",
    "Totalizador_Aire_L3",
    "KW Bba Glicol Sala MAq",
    "Restos Planta (Kw)",
    "Totaliador_Aire_L4",
    "Agua Cocina / Hl",
    "Cocina (Kw)",
    "CO 2 Filtro / Hl",
    "Red Lavadora L3",
    "KW Mycom 3",
    "Medicion Gas Planta (M3)",
    "EE Frio / Hl",
    "FC CIP Bodega",
    "Totalizador_Bodega",
    "Agua Calderas",
    "Hl Cerveza L4"
]

